Repository PetroFit/petrofit, pull requests merged in 2024-10, with the labels that each got.

#220 Misc fixes noticed during PyOpenSci review
  docs/correction_grids.ipynb
  docs/fitting.ipynb
  docs/fitting_workflow.ipynb
  docs/introduction.ipynb
  docs/multi_object.ipynb
  docs/petrosian.ipynb
  docs/photometry.ipynb
  docs/quick_start.ipynb
  petrofit/modeling/fitting.py
  petrofit/petrosian/core.py
  petrofit/photometry.py
  petrofit/segmentation.py
Labels: pyOpenSci

#222 PYOS Review Updates [Infrastructure]
  .editorconfig
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/02-question.yml
  .github/ISSUE_TEMPLATE/03-feature-request.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/SUPPORT.md
  .github/workflows/ci_tests.yml
  .github/workflows/main.yml
  .github/workflows/test.yml
  .gitignore
  .readthedocs.yaml
  Dockerfile
  README.rst
  docker.py
  docs/conf.py
  environment.yml
  petrofit/__init__.py
  petrofit/_astropy_init.py
  petrofit/data/README.rst
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  tox.ini
Labels: Testing, Installation, Backwards Incompatible, Infrastructure, Major, pyOpenSci

#225 Patch test badge
  .github/workflows/test.yml
  README.rst
Labels: Documentation

#227 Add coverage test
  .github/workflows/test.yml
  README.rst
Labels: Testing, pyOpenSci
